spring:
  application:
    name: installations-service
  datasource:
    url: jdbc:postgresql://localhost:5432/installationsdb
    username: postgres
    password: "123456"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: InstallationsHikariCP
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  cloud:
    loadbalancer:
      retry:
        enabled: true
        max-retries-on-same-service-instance: 2
        max-retries-on-next-service-instance: 3
        retryable-status-codes: 500,502,503,504
    circuitbreaker:
      resilience4j:
        instances:
          users-service:
            register-health-indicator: true
            sliding-window-size: 10
            minimum-number-of-calls: 5
            permitted-number-of-calls-in-half-open-state: 3
            automatic-transition-from-open-to-half-open-enabled: true
            wait-duration-in-open-state: 5s
            failure-rate-threshold: 50
            event-consumer-buffer-size: 10

server:
  port: 8091
  servlet:
    context-path: /api/installations
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 1024

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    instance-id: ${spring.application.name}:${server.port}
    metadata-map:
      zone: primary
      instance-group: installations-group

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: basic
      ORDERS-MICROSERVICE:
        connect-timeout: 6000
        read-timeout: 6000
      USERS-MICROSERVICE:
        connect-timeout: 6000
        read-timeout: 6000
        logger-level: full
  circuitbreaker:
    enabled: true
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
    connection-timeout: 5000
    follow-redirects: true
  compression:
    request:
      enabled: true
    response:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      orders-service:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
      users-service:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
  retry:
    instances:
      orders-service:
        maxAttempts: 3
        waitDuration: 1000ms
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
      users-service:
        maxAttempts: 3
        waitDuration: 1000ms
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /management
      path-mapping:
        health: healthcheck
  endpoint:
    health:
      show-details: always
      show-components: always
      group:
        custom:
          include: db,diskSpace
    metrics:
      enabled: true
    prometheus:
      enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    defaults:
      enabled: false
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.cloud: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example.installations_microservice: DEBUG
    feign: DEBUG
    com.netflix: WARN
  file:
    name: logs/installations-service.log
    max-history: 7
    max-size: 10MB
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

security:
  basic:
    enabled: false
  oauth2:
    client:
      registration:
        keycloak:
          client-id: installations-service
          client-secret: change-me
          scope: openid,profile,email
          authorization-grant-type: client_credentials
      provider:
        keycloak:
          issuer-uri: http://localhost:8080/auth/realms/master